### PR TITLE
Add parameter return-license in build job

### LINKED ISSUE #26: Make return_license step in main job optional
## Orb version:

1.0.0

## What happened:

When running with the unity-orb job, the build may succeed but then the "return license" step will run and fail:

```
LICENSE SYSTEM [2022831 1:41:30] Error fetching https://license.unity3d.com/update/poll?cmd=3&tx_id=41355cad154aaa5bf83f36699f935631
serial was activated manually for this computer and can't be returned

LICENSE SYSTEM [2022831 1:42:0] Failed to return license: Unity license return request has timed out. Please verify that you are connected to the Internet and/or try again later.
```

This is with a personal license. I followed the steps [here](https://game.ci/docs/circleci/activation#personal-license).

## Expected behavior:

Well, ideally the Unity service wouldn't return an error, it'd just say "okay thanks but I can't do anything with that."

## Additional Information:

This forced me to decompose the job into its constituent commands, but...I'd have to do that anyway for my other "persist_to_workspace" issues mentioned in my other ticket (#25).

But if it wasn't for that, I'd be happy with any of the following options:
* Tell unity-orb I'm using a personal license, so it doesn't try to return it (since it was manually activated).
* Tell unity-orb I'm using a manually-activated license directly, so it doesn't try to return it.
* Have unity-orb check for "activated manually for this computer and can't be returned", or an HTTP status code (?), and ignore non-fatal errors from the Unity server.

### PR DESCRIPTION
**Pull request by tadashi0713**
https://game.ci/docs/github/returning-a-license

Since Unity only allows returning professional licenses, I added a parameter to switch whether returning licenses or not for other types of licenses.

### CODE REVIEW

**Comment by EricRibeiro** [comment]
Thanks, @tadashi0713 🙇 

Weird that shellcheck is complaining since you didn't touch any script. Nevertheless, is a valid error that it caught, so I'll go ahead and open a PR with the fix and then we can merge yours.

**Comment by nanodeath** [comment]
Speaking as a free Unity user, it'd be kinda nice if the default just worked. Can we always have this orb try to return the license, and fail gracefully and continue if it can't? Or is that a recipe for problems.

**Comment by EricRibeiro** [comment]
> Speaking as a free Unity user, it'd be kinda nice if the default just worked. Can we always have this orb try to return the license, and fail gracefully and continue if it can't? Or is that a recipe for problems.

I don't believe it's a problem in most cases. However, It would make your job run time unnecessarily longer. The doc linked by @tadashi0713 says:

> Manually returning a license is usually never necessary, unless when running into an unrecoverable error while having a license active.
> 
> Also, Unity only allows returning professional licenses.

Meaning that even for Pro and Plus, it's not always necessary to return the license. Perhaps the best approach is to set the new parameter to `false` as the default. What do you all think @nanodeath and @tadashi0713?

**Comment by EricRibeiro** [comment]
Also, @tadashi0713, can I ask you to include the new parameter in the `test` job? We will need it there, too, since it also uses the `return-license` command.

**Comment by EricRibeiro** [comment]
Pushed the change with my suggestions and merged the shellcheck fix, let me know what you all think.

**Comment by nanodeath** [comment]
Looks good to me.

**Comment by tadashi0713** [comment]
@EricRibeiro Thank you for your suggestion/fix, also looks good to me 👍

**Review by KyleTryon — APPROVED** [review]

**Comment by KyleTryon** [comment]
Looks like this resolves #26

**Pull request merged**
