### PR TITLE
Fix macOS Executors

### LINKED ISSUE #71: Job was rejected because resource class large, image xcode:13.4.1 is not a valid resource class
I updated a few things and merged some PRs in `main`, the pipelines are failing:

https://app.circleci.com/pipelines/github/game-ci/unity-orb/319/workflows/9385a9fb-c170-4656-84cf-4eb1a37bda94

CleanShot 2024-06-12 at 15 02 23

We probably only need to update the macos runners version. This project hasn't moved for a while.

Problem is located here:

https://github.com/game-ci/unity-orb/blob/8dadf8a039c4fe910357c8015605fb799cb2dbbb/src/executors/macos.yml#L24-L24

### PR DESCRIPTION
**Pull request by GabLeRoux**
Closes https://github.com/game-ci/unity-orb/issues/71

### CODE REVIEW

**Comment by GabLeRoux** [comment]
> Job was rejected because resource class large, image xcode:15.3.0 is not a valid resource class

🤔

**Comment by thedrhax14** [comment]
On top of that it is unable to activate unity license ([here](https://app.circleci.com/pipelines/github/game-ci/unity-orb/322/workflows/53a92683-693b-4590-96af-e637609074c6/jobs/4064) at line 33)

**Comment by GabLeRoux** [comment]
Indeed, license activation that is failing is likely due to changes from Unity. I [wrote a fix for gitlab-ci a while back](https://gitlab.com/game-ci/unity3d-gitlab-ci-example/-/merge_requests/95) (which omg I should definitely merge, I'll find some time this summer to clean things up).

We're basically activating by extracting a serial out of a free license file.

**Comment by GabLeRoux** [comment]
I'm not actively using this orb, but if anyone would like to help me bring this back up and running, don't hesitate to ping me and I'll create a release once we get the activation working again 🙏

**Comment by GabLeRoux** [comment]
I managed to get the macOs jobs to run again by using `macos.m1.medium.gen1`, but now they're failing with activation. I would say it is now better than it used to be. All we need is to fix the activation steps which we can inspire by what was [done in here](https://gitlab.com/game-ci/unity3d-gitlab-ci-example/-/merge_requests/95).

More precisely [in `before_script.sh`](https://gitlab.com/game-ci/unity3d-gitlab-ci-example/-/blob/cc50193350429ee6d27cb11e026ea826a54bd331/ci/before_script.sh)

**Comment by thedrhax14** [comment]
> I managed to get the macOs jobs to run again by using `macos.m1.medium.gen1`, but now they're failing with activation. I would say it is now better than it used to be. All we need is to fix the activation steps which we can inspire by what was [done in here](https://gitlab.com/game-ci/unity3d-gitlab-ci-example/-/merge_requests/95)

(1) Does it mean an actual license (at least personal license) should be used? (2) As far as I understood anyone who has the environment variables for unity license set in their circleci account then the pipeline should work, right? (3) Or is it still necessarily to update the sh scripts as well?

**Comment by GabLeRoux** [comment]
> (1) Does it mean an actual license (at least personal license) should be used? 

I think there's already one configured for the current repository in CircleCI's side. Or it used to. On Github side, we set these env vars for the github actions to properly test the actions:

* UNITY_EMAIL
* UNITY_LICENSE
* UNITY_PASSWORD
* UNITY_SERIAL

> (2) As far as I understood anyone who has the environment variables for unity license set in their circleci account then the pipeline should work, right?

I'm not a 100% sure. This would be preferable indeed, but we're facing the activation issues with the version 3.x.x of the Docker images which might be a breaking change for activation so I wouldn't count too much on it.

To do this the right way, we should keep fixing things and then decide if we release `1.8.0` or `2.0.0` for this orb. The only way we can confirm this would be to have an already working project with orb running on `1.7.0` and then try the pipelines again with updated codebase (once we fix the activation scripts in current repo).

> (3) Or is it still necessarily to update the sh scripts as well?

I think so.

**Comment by GabLeRoux** [comment]
I'll merge this in main branch as well (`main` branch is already unstable and wasn't up to date with latest Unity versions anyway).

At least we're using updated macOS Executors in here now 🚀 

Let's figure out the best way to solve activation for this orb and bring it back to life :)

**Comment by thedrhax14** [comment]
> I think there's already one configured for the current repository in CircleCI's side. Or it used to. On Github side,

My only suspicion after inspecting last [pipeline ](https://app.circleci.com/pipelines/github/game-ci/unity-orb/328/workflows/cb7571ed-d3aa-426c-8bf7-15d424cb5a0d) is that current UNITY_LICENSE or UNITY_SERIAL is either revoked or expired. I hope I was looking at a right part of it

**Comment by GabLeRoux** [comment]
> > I think there's already one configured for the current repository in CircleCI's side. Or it used to. On Github side,
> 
> My only suspicion after inspecting last [pipeline ](https://app.circleci.com/pipelines/github/game-ci/unity-orb/328/workflows/cb7571ed-d3aa-426c-8bf7-15d424cb5a0d) is that current UNITY_LICENSE or UNITY_SERIAL is either revoked or expired. I hope I was looking at a right part of it

That sounds right, I'll see if I have access to the settings and fill some of them again. 
_edit1: I currently don't have access to the secrets. I'll try to reach original authors or CircleCI and see what we can do 🙏_ 
_edit2: I had to re-authorize my github link in CircleCI and I now have access to the org, I'll be able to update the secrets if needed_.

**Comment by GabLeRoux** [comment]
I've created two followup issues:

* https://github.com/game-ci/unity-orb/issues/73
* https://github.com/game-ci/unity-orb/issues/74

I'll ping some people around to see if they can help.

**Pull request merged**
